# Write a "Guess the number". Use the random module to generate a random number (target, 
# in the code below) between 1 and 20. Then the user will input an integer. 
# If the input is equal to the random number generated by the program, the program ends. 
# If the input number is larger than the random number, 
# the program will tell the user that the guess was too high. Otherwise it will tell the user 
# that the guess was too low. The user has, at most, 5 guesses.


import random

target = random.randint(1,20)
